### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by job-1994** [lambdaloop/checkerboard#1]
After including the line "from checkerboard import detect_checkerboard", and attempting to run the python script I get the following error:

Traceback (most recent call last):
  File "/home/job/repos/realtime-system/src/camera_calibration_3di/scripts/test.py", line 7, in <module>
    import checkerboard
  File "/usr/local/lib/python2.7/dist-packages/checkerboard/__init__.py", line 6, in <module>
    from . import checkerboard
  File "/usr/local/lib/python2.7/dist-packages/checkerboard/checkerboard.py", line 259
    corners_reshaped = corners[:, :2].reshape(*size, 2)
SyntaxError: only named arguments may follow *expression

I will attempt to fix myself but wanted to inform you of this error. If you have any suggestions let me know

**Comment by job-1994** [comment]
I see now that the issue is likely due to me running Python 2.7 on my machine. I will switch to Python 3 in the near future which should fix this issue

**Comment by lambdaloop** [comment]
That's right, checkerboard has only been tested on Python 3 so far. I don't expect to support Python 2 in the future.
